# Generated by Django 3.2.2 on 2021-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_icons_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificBanner',
            fields=[
                ('sb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sb_category', models.CharField(default='', max_length=100)),
                ('sb_img1', models.ImageField(blank=True, default='', null=True, upload_to='shop/specific_banners')),
                ('sb_img2', models.ImageField(blank=True, default='', null=True, upload_to='shop/specific_banners')),
            ],
        ),
    ]
